[project]
name = "webrtc-test"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

dependencies = [
    "aiohttp>=3.13.1",
    "aiortc>=1.14.0",
    "openai>=2.5.0",
    "opencv-python>=4.12.0.88",
    "scipy>=1.16.2",
    "websockets>=15.0.1",
]
